<?php
// $Id$

/**
 * @file
 * The main module file for capn_hook module.
 */

/**
 * Implementation of hook_perm().
 */
function capn_hook_perm() {
  return array('sail the seven seas');
}

/**
 * Implementation of hook_nodeapi().
 */
function capn_hook_nodeapi(&$node, $op, $teaser = TRUE, $page = FALSE) {
  switch ($op) {
    case 'view':
      if ($page) {
        $_SESSION['capn_hook_stats'][$node->nid]++;
        
        $node->content['capn_hook_stats'] = array(
          '#value' => t('You have viewed this page %num times', array('%num' => $_SESSION['capn_hook_stats'][$node->nid])),
          '#weight' => 10,
        );
      }
  }
}

/**
 * Implementation of hook_user().
 */
function capn_hook_user($op, &$edit, &$account) {
  switch ($op) {
    case 'form':
      if (user_access('sail the seven seas')) {
        $form = array();
        $form['is_pirate'] = array(
          '#type' => 'radios',
          '#title' => t('I am a pirate'),
          '#options' => array(0 => t('No'), 1 => t('Yes')),
          '#default_value' => $edit['is_pirate'],
        );
      }
      return $form;
      break;
      
    case 'view':
      if ($account->is_pirate) {
        $account->content['capn_hook'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Yarr!'),
          '#value' => theme('capn_hook_user', $account),
          '#weight' => 10,
        );
      }
      break;
  }
}

/**
 * Implementation of hook_theme()
 */
function capn_hook_theme() {
  return array(
    'capn_hook_user' => array(
      'arguments' => array('account' => NULL)
    )
  );
}

/**
 * Theme 'capn_hook_user' to just output a picture of Captain Hook.
 */
function theme_capn_hook_user($account) {
  $output = '<img src="http://tinyurl.com/279qnf" alt="ahoy!" />';   
  return $output;
}

